app_name: "T&T Purchase Order Processor"
version: "1.0.0"

odoo:
  default_url: "https://atiara-trading-inc.odoo.com"
  default_db: "atiara-trading-inc"

supabase:
  project_id: "wfgxdqblcoxzspbrwpmh"
  url: "https://wfgxdqblcoxzspbrwpmh.supabase.co"

warehouse_mapping:
  cw_stores: [1, 3, 4, 5, 6, 7, 8, 10, 13, 14, 17, 19, 23, 24, 25, 26, 29, 30, 31, 33, 36]
  # All other stores are implicitly CE

processing:
  min_order_qty: 1
  # latest_so_number should be entered manually in the UI (no default)

tt_store_names:
  1: 'T&T Supermarket Inc., Metrotown  - 001'
  3: 'T&T Supermarket Inc., Chinatown  - 003'
  4: 'T&T Supermarket Inc., First Avenue  - 004'
  5: 'T&T Supermarket Inc., Osaka  - 005'
  6: 'T&T Supermarket Inc., Surrey  - 006'
  7: 'T&T Supermarket Inc., Calgary  - 007'
  8: 'T&T Supermarket Inc., Coquitlam  - 008'
  9: 'T&T Supermarket Inc., Promenade Store - 009'
  10: 'T&T Supermarket Inc., Edmonton  - 010'
  11: 'T&T Supermarket Inc., Warden&Steels Store - 011'
  13: 'T&T Supermarket Inc., Central City  - 013'
  14: 'T&T Supermarket Inc., Harvest Hills  - 014'
  15: 'T&T Supermarket Inc., Central Parkway Store - 015'
  17: 'T&T Supermarket Inc., Northtown Edmonton  - 017'
  18: 'T&T Supermarket Inc., Ottawa Store - 018'
  19: 'T&T Supermarket Inc., Park Royal  - 019'
  20: 'T&T Supermarket Inc., Weldrick Store - 020'
  21: 'T&T Supermarket Inc., Woodbine Store - 021'
  22: 'T&T Supermarket Inc., Unionville Store - 022'
  23: 'T&T Supermarket Inc., Ora  - 023'
  24: 'T&T Supermarket Inc., SE Edmonton  - 024'
  25: 'T&T Supermarket Inc., Marine Gateway  - 025'
  26: 'T&T Supermarket Inc., Lansdowne  - 026'
  27: 'T&T Supermarket Inc., Aurora Store - 027'
  28: 'T&T Supermarket Inc., Waterloo Store - 028'
  29: 'T&T Supermarket Inc., Kingsway  - 029'
  30: 'T&T Supermarket Inc., Deerfoot  - 030'
  31: 'T&T Supermarket Inc., Langley  - 031'
  32: 'T&T Supermarket Inc., College Store - 032'
  33: 'T&T Supermarket Inc., Sage Hill  - 033'
  34: 'T&T Supermarket Inc., St.Croix Store - 034'
  35: 'T&T Supermarket Inc., Fairview Mall Store - 035'
  36: 'T&T Supermarket Inc., Lougheed  - 036'
  37: 'T&T Supermarket Inc., London Store - 037'
  38: 'T&T Supermarket Inc., Downtown Store - 038'
  39: 'T&T Supermarket Inc., Kanata Store - 039'
  40: 'T&T Supermarket Inc., Brossard Store - 040'
